### ISSUE TITLE
Fluid drag problem in cordova

### ISSUE THREAD

**Issue by mantua75** [emilhem/interact-cordova-testing#1]
Hi,
I'm trying to implement interact.js into my Cordova project but I have fluency problems. The movement of the objects is not flowing and stops after a few movements even if the drag action is not finished.

I find the same problem in my project and with "interact-cordova-testing" example.

Could someone help me?

Thanks!

**Comment by emilhem** [comment]
Hmm, I don't use Cordova at the moment so I can't test this.

I'm not a developer of either Cordova nor Interact so I can't really give you support for any of those. My recommendation is to ask such questions on [StackOverflow](https://stackoverflow.com/) but remember that nobody has any obligation to give you an answer.

Remember to be very thorough when asking questions. Add any detail that could help others in helping you such as Android version, Cordova version, Interact.js version, Android SDK version. If you can you should provide the source code of a minimal use case where the issue occurs.
